ADD: Day 01, 02, 03
BlueCat-Community/10-Days-Of-DL pull request #9
Opened 2019-10-16 14:26 UTC by starfishda

issue #1 
Add day 01, 02, 03

2019-10-16 14:36 UTC, banksemi commented on Day1/Lab01.ipynb
> +{
<p>아직도 잘 이해가 안되는 부분이 하나 있는데</p><p> </p><p>&lt;code&gt;@tf.function&lt;/code&gt;의 역할을 잘 모르겠습니다 ! ㅠㅠ</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/BlueCat-Community/10-Days-Of-DL/pull/9/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2019-10-16 14:50 UTC, KimDoubleB commented on Day1/Lab01.ipynb
> +{
tf.function 데코레이터를 사용하면 그래프로 컴파일되며 해당 함수와 이 함수가 호출하는 모든 함수는 GPU 또는 TPU에서 실행되거나 세이브드모델(SavedModel)로 내보내 더 빠른 실행 속도를 얻을 수 있다고 합니다.

참조: https://www.tensorflow.org/guide/function?hl=ko

그리고 코드 리뷰는 py파일에 부탁드립니다.

2019-10-16 14:57 UTC, banksemi commented on Day1/Lab01.ipynb
> +{
네 알겠습니다 !
감사합니다~~~

2019-10-16 15:14 UTC, KimDoubleB requested changes

2019-10-16 15:14 UTC, KimDoubleB commented on Readme.md
> +##Hello World
이거 삭제 해주세요.

2019-10-17 01:02 UTC, starfishda commented on Readme.md
> +##Hello World
수정했습니다.

2019-10-17 01:15 UTC, KimDoubleB commented on Readme.md
> +##Hello World
파일 삭제 말한건데, 파일 삭제하신건가요?

2019-10-17 01:36 UTC, rurimo approved these changes
👍 👍

2019-10-17 01:44 UTC, starfishda commented on Readme.md
> +##Hello World
넵!! 삭제까지 했습니다!!

2019-10-17 02:49 UTC, Jung-Juhwan commented on Day1/Lab01.py
> +@tf.function # session 대신 사용
@tf.function # use instead of session

2019-10-17 11:36 UTC, jackinsjh approved these changes

2019-10-17 14:12 UTC, Jo-kyeong-ho approved these changes

2019-10-17 15:07 UTC, soyoungpark9187 reviewed
이미지로 정리되어있어서 이해하기 편했습니다~

2019-10-17 15:38 UTC, KimDoubleB approved these changes

2019-10-18 03:31 UTC, merged